name: Deploy to Droplet

on:
  push:
    branches: [main]  # or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            bash /root/scripts/update.sh
