name: Deploy to Droplet

on:
  push:
    branches: [master]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            bash ${{ secrets.DEPLOY_SCRIPT }}
